name: 🐛 Bug report
description: Report a bug to help us improve Gin-Vue-Admin
title: "[Bug]: "
labels: [bug]
assignees:
  - piexlmax
  - songzhibin97
  - SliverHorn
  - bypanghu
body:
  - type: input
    id: gva
    attributes:
      label: gin-vue-admin version
      description: Please enter the project version you are currently using?
      placeholder: 2.4.5Beta
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node version
      description: Please enter the NODE version you are currently using?
      placeholder: v14.16.0
    validations:
      required: true
  - type: input
    id: golang
    attributes:
      label: Golang version
      description: Please enter the GOLANG version you are currently using?
      placeholder: go 1.16
    validations:
      required: true
  - type: dropdown
    id: reappearance
    attributes:
      label: does it still exist?
      description: Is it possible to reproduce this bug in the master branch?
      options:
        - Can
        - Can't
        - not tested
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: bug description
      description: Please briefly describe the bug and the reproduction process.
      placeholder: |
        1. First...
        2. Then...
    validations:
      required: true
  - type: textarea
    id: advise
    attributes:
      label: modification suggestions
      description: If you have any good suggestions or modifications, please provide them to us.
