name: 🚀 Feature request
description: Suggest an idea for Gin-Vue-Admin
title: "[Feature]: "
labels: [feature]
assignees:
  - piexlmax
body:
  - type: textarea
    id: desc
    attributes:
      label: Function description and necessity description
      description: What convenience do you think this new feature will bring to the framework.
      placeholder: |
        1. First...
        2. Then...
    validations:
      required: true
  - type: textarea
    id: advise
    attributes:
      label: suggestions and solutions
      description: If you have any good suggestions or modifications, please provide them to us.
